services:
  - type: web
    name: plant-disease-detector-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cp -r backend/* .
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 8000

  - type: static
    name: plant-disease-detector-frontend
    buildCommand: cd frontend && echo "Building frontend..."
    staticPublishPath: ./frontend
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*" 